[package]
name = "pake"
version = "3.1.2"
description = "🤱🏻 Turn any webpage into a desktop app with Rust."
authors = ["Wick"]
license = "MIT"
repository = "https://github.com/WhiteLeee/Pake"
edition = "2021"
rust-version = "1.78.0"

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "lib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2.0.4", features = [] }

[dependencies]
log = "0.4.22"
url = "2.5.2"
reqwest = { version = "0.12.5", features = ["blocking", "json", "multipart", "rustls-tls"], default-features = false }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0"
zip = { version = "0.6", default-features = false, features = ["deflate"] }
chrono = { version = "0.4", features = ["serde"] }
tokio = { version = "1.42.0", features = ["full"] }
tauri = { version = "2.2.0", features = ["tray-icon", "image-ico", "image-png", "macos-proxy"] }
tauri-plugin-window-state = "2.2.0"
tauri-plugin-oauth = "2.0.0"
tauri-plugin-store = "2.0.0"
tauri-plugin-clipboard-manager = "2.0.0"
once_cell = "1.19.0"
tauri-plugin-global-shortcut = "2.0.0-beta.7"
tauri-plugin-single-instance = "2.0.0-beta.5"
tauri-plugin-shell = "2.0.0"
tauri-plugin-dialog = "2.0.0"
tauri-plugin-notification = "2.0.0"
tauri-plugin-fs = "2.0.0"
tauri-plugin-http = "2.0.0"
tauri-plugin-os = "2.0.0"
dirs = "5.0"

[features]
# this feature is used for development builds from development cli
cli-build = []
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = ["custom-protocol"]
# this feature is used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = ["tauri/custom-protocol"]
